[2016-04-05 10:00:08,478 INFO root] Taurus CLI Tool v1.3.3
[2016-04-05 10:00:08,479 DEBUG root] Command-line options: {'verbose': None, 'no_system_configs': None, 'quiet': None, 'log': 'bzt.log', 'option': None, 'aliases': []}
[2016-04-05 10:00:08,481 DEBUG root] Python: CPython 2.7.10
[2016-04-05 10:00:08,482 DEBUG root] OS: ('Darwin', 'mondosage.local', '15.3.0', 'Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64', 'x86_64', 'i386')
[2016-04-05 10:00:08,584 INFO root] Starting with configs: ['login.yml']
[2016-04-05 10:00:08,584 INFO Engine] Configuring...
[2016-04-05 10:00:08,584 DEBUG Engine] Reading machine configs from: /etc/bzt.d
[2016-04-05 10:00:08,585 DEBUG Engine] Adding personal config: /Users/sage/.bzt-rc
[2016-04-05 10:00:08,585 DEBUG Engine.Configuration] Configs: ['/etc/bzt.d/10-base.json', '/etc/bzt.d/99-installID.yml', '/Users/sage/.bzt-rc']
[2016-04-05 10:00:08,585 DEBUG Engine.Configuration] Reading /etc/bzt.d/10-base.json as JSON
[2016-04-05 10:00:08,586 DEBUG Engine.Configuration] Reading /etc/bzt.d/99-installID.yml as YAML
[2016-04-05 10:00:08,587 DEBUG Engine.Configuration] Reading /Users/sage/.bzt-rc as YAML
[2016-04-05 10:00:08,588 DEBUG Engine.Configuration] Configs: ['login.yml']
[2016-04-05 10:00:08,589 DEBUG root] Caught exception in try: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/bzt/cli.py", line 140, in perform
    self.engine.configure(configs, not self.options.no_system_configs)
  File "/Library/Python/2.7/site-packages/bzt/engine.py", line 88, in configure
    merged_config = self._load_user_configs(user_configs)
  File "/Library/Python/2.7/site-packages/bzt/engine.py", line 415, in _load_user_configs
    self.config.load(user_configs)
  File "/Library/Python/2.7/site-packages/bzt/engine.py", line 550, in load
    config = self.__read_file(config_file)[0]
  File "/Library/Python/2.7/site-packages/bzt/engine.py", line 566, in __read_file
    with open(filename) as fds:
IOError: [Errno 2] No such file or directory: 'login.yml'

[2016-04-05 10:00:08,589 ERROR root] IOError: [Errno 2] No such file or directory: 'login.yml'
[2016-04-05 10:00:08,589 WARNING root] Please wait for graceful shutdown...
[2016-04-05 10:00:08,589 INFO Engine] Post-processing...
[2016-04-05 10:00:08,589 INFO root] Artifacts dir: None
[2016-04-05 10:00:08,589 WARNING root] Done performing with code: 1
[2016-04-05 10:00:08,590 DEBUG Engine] Add existing artifact (move=True): bzt.log
[2016-04-05 10:00:08,590 WARNING Engine] Artifacts dir has not been set, will not copy bzt.log
